### ISSUE TITLE
TODO tasklist

### ISSUE THREAD

**Issue by aviralrabbit1** [aviralrabbit1/nasa-project#9]
### Discussed in https://github.com/aviralrabbit1/nasa-project/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **aviralrabbit1** August 24, 2023</sup>
Tasklist for Project
- [x] Launches model
- [x] GET /launches
- [x] Serving Applications With Client Side Routing
- [x] Building a Data Access Layer [Layered Architecture]
- [x] Post /launches
- [x] Validating Post /launches data
- [x] Communication with frontend
- [x] DELETE /launches: Aborting Launches</div>

**Comment by aviralrabbit1** [comment]
All Done!!
